image:
  repository: 018882981263.dkr.ecr.ap-southeast-1.amazonaws.com/final-project-ecr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

replicaCount: 2

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization:
    targetAverageUtilization: 70

config:
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: "pass9764gd"
  ALLOWED_HOSTS: "*"

ingress:
  enabled: false
  className: nginx
  host: django.example.com
  path: /
  pathType: Prefix
  tls: false